# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78608c115c588481b33a861af297ea476d08fa4c6bbf110b5cd4cc1b485b543c21170591e1ee571d2bbc7d705c1b8a1a141bbf8dee3009f8983c2ed18f7c2fd0

test:
  secret_key_base: e50a3c4207a3ada5b4f28c127118e0c17b8b55b1287cd24f07cfb1c9e0f713ac1639baad3139e98097dc425bd344fcd9d8b629081a5dfd5b2233b32d7db9aa83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
